### PR TITLE
Fix Release folder not being created

### PR DESCRIPTION
**Pull request by samuel100u**
Screenshot 2021-12-03 120735

### CODE REVIEW

**Comment by shepark** [comment]
@samuel100u Please provide more information when you create PR.
For example,
[Issue]: what the problem is ( with steps to reproduce)
[Solution]: how you fix
[Test]: how to test

**Comment by shepark** [comment]
@samuel100u You don't need to worry about the "Release" folder.
If you succeed to finish the build, then you will see "_deps" folder and it will contain all the outputs.

**Comment by samuel100u** [comment]
> don't need to worry about the "Release" folder.
> If you succeed to finish the build, then you will see "_deps" folder and it wi

yes, but the "Release" file is not a folder.

**Comment by mav-intel** [comment]
@samuel100u Thanks for the PR.  It was merged in 4f0384ece28aa25e0cb01cc76eb9ca1ef64ca297. Had to do some slight formatting changes to pass lint.

**Pull request closed without merging**
